### PR TITLE
iOS Eddystone support

### PR DESCRIPTION
**Pull request by jampueroc**
Hi, I added secureProfileListener that come from version 3.3.2 in android

### CODE REVIEW

**Comment by Andruschenko** [comment]
Thanks for the great PR! I saw you did not only update the Android SDK, but also updated the iOS SDK and added iOS eddystone methods!
Great work! I want to test your code over the easter holidays and then merge. The README and the example app should be updated as well then!

**Comment by jampueroc** [comment]
Hi, I am really happy that you see my work, this weekend I can help updating documentation :)

Test my fork to check that all works fine before submit anoyther PR

**Comment by Andruschenko** [comment]
I'd like to split this up into two PRs since you're doing very different things here. I cherry-picked the first two commits of this PR into a new branch https://github.com/Artirigo/react-native-kontaktio/tree/android-sdk-update-to-4 in which I'll update to the newest Kontakt.io SDK version.

@jampueroc Could you file another PR with the last four commits which are about updating the iOS part? I will then review that separately.

**Comment by Andruschenko** [comment]
@is343 I hoped for @jampueroc to update the documentation about these methods, but there nothing will happen probably. If you'd update the documentation with the new functions, I'd be very happy about the PR!

**Comment by nicholasc** [comment]
I would love to do the documentation on this. Should I create a separate PR for this? Since @jampueroc  is not responding anymore I doubt he would merge my change to his fork in order to update this.

Let me know how you want to achieve this.

**Comment by Andruschenko** [comment]
@nicholasc Excellent! I appreciate it a lot! Yes, please create a second PR for it.

Did you test this branch? Does it work fine for you?

Another thing I want to do is to update the example app. Do you happen to use it? If so, it would be great if you could share your version using these new functions. If not, never mind.

The example app already got quite old now. I might open up a ticket to improve it.

**Comment by nicholasc** [comment]
I just tested it on iOS and it works fine. I am going to give it a spin on Android and then start writing appropriate documentation for it. I'll keep you posted.

**Pull request merged**
