### PR TITLE
Update setup.ios.md

### PR DESCRIPTION
**Pull request by nylsoo**
Had to add the 
NSLocationAlwaysAndWhenInUseUsageDescription otherwise it wouldn't ask for location

### CODE REVIEW

**Comment by Andruschenko** [comment]
Thanks for the addition. You were not able to run it with either of the other location related permissions?

**Comment by nylsoo** [comment]
No, when adding the 2 permissions i got an error saying i should add NSLocationAlwaysAndWhenInUseUsageDescription as well.

**Comment by Andruschenko** [comment]
Interesting.. so you had to add all three permission?

**Comment by Andruschenko** [comment]
Updated it to reflect that one permission got deprecated.

**Pull request merged**
